from .orders.VideoProducer import VideoProducer
from .orders.Brand import Brand
from .orders.AdvertisementVideo import AdvertisementVideo
from .orders.Chain import Chain
from .orders.Supermarket import Supermarket
from .orders.Department import Department
from .orders.SupermarketAddress import SupermarketAddress
from .orders.PanelManufacturer import PanelManufacturer
from .orders.Panel import Panel
from .orders.PanelVideo import PanelVideo
from .orders.Resolution import Resolution
from .orders.ScreenSize import ScreenSize
from .orders.RefreshRate import RefreshRate
from .orders.TechnicalSpecifications import TechnicalSpecifications
