COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql://{}:{}@superdbyou.mysql.database.azure.com/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://{}:{}@superdbyou.mysql.database.azure.com/lab4'

ADDITIONAL_CONFIG: {}